/* GPT Austral Wash Bay — standalone application */
(()=>{'use strict';
const V=document.querySelector('#view'),T=document.querySelector('#pageTitle'),HOME=document.querySelector('#homeButton');
const S={screen:'home',type:null,sel:null,i:0,steps:[],timer:null,remaining:0};
const esc=x=>String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const $=s=>document.querySelector(s);
function bodyParts(value,sel){if(value==null)return[];if(Array.isArray(value))return value.flatMap(v=>typeof v==='object'?conditional(v,sel):[v]);if(typeof value==='object')return conditional(value,sel);return[value]}
function conditional(o,sel){const key=Object.keys(o)[0];if(!key)return[];const rules={noCoating:()=>sel.coating==='none',turtle:()=>sel.coating==='turtlewax',touchon:()=>sel.coating==='touchon',rainx:()=>sel.glass==='rainx',noRainx:()=>sel.glass!=='rainx',claybarTarRemoval:()=>!!sel.claybarTarRemoval,wheelsDeep:()=>!!sel.wheelsDeep,ironFallout:()=>!!sel.ironFallout,snowFoamRegular:()=>sel.snowFoam==='regular',snowFoamDeep:()=>sel.snowFoam==='deep'};return(!rules[key]||rules[key]())?[o[key]]:[]}
function renderContent(value,sel){return bodyParts(value,sel).map(v=>`<p>${v}</p>`).join('')}
function renderWarning(value,sel){const parts=bodyParts(value,sel);return parts.length?`<div class="warning">${parts.join('<br>')}</div>`:''}
function home(){clearInterval(S.timer);S.timer=null;S.screen='home';T.textContent='Wash Planner';V.innerHTML=`<section class="hero dashboard"><div class="hero-copy"><span class="eyebrow">TODAY'S WASH WINDOW</span><h2>Ready when the conditions are.</h2><p>Your car, protection and weather — brought together in one glance.</p></div><div class="glance"><div><div class="orbit protection"><div><small>PROTECTION</small><strong>—</strong><span>checking</span></div></div><div class="glance-label">PROTECTION</div></div><div><div class="glance-detail"><span class="weather-icon">⛅</span><strong>—°</strong><small>weather loading</small><b>CHECKING</b></div><div class="glance-label">RIGHT NOW</div></div><div><div class="orbit weather-orbit"><div class="weather-hours"><span>—<br>◌<br>—</span><span>—<br>◌<br>—</span><span>—<br>◌<br>—</span><span>—<br>◌<br>—</span></div></div><div class="glance-label">NEXT HOURS</div></div></div><div class="status-line"><span class="status-dot"></span><strong>Wash planner ready</strong><span>Weather engine next</span></div></section><section class="cards"><div class="info-card"><span class="eyebrow">WASH RHYTHM</span><h3>Choose the wash when you're ready</h3><p>The guided journey will use the canonical wash instructions and only show steps relevant to your choices.</p></div><div class="info-card"><span class="eyebrow">PROTECTION</span><h3>Coating-aware from the first step</h3><p>Only one coating can be selected per wash. Conditional instructions are assembled automatically.</p></div></section><div class="wash-choice"><button class="choice action" data-type="regular"><h3>Regular wash <span>→</span></h3><p>Routine maintenance · streamlined guided route</p></button><button class="choice action" data-type="deep"><h3>Deep wash <span>→</span></h3><p>Full clean · decontamination · detail</p></button></div>`;document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>setup(b.dataset.type))}
function setup(type){S.type=type;S.screen='setup';T.textContent='New Wash';V.innerHTML=`<section class="hero setup"><span class="eyebrow">${type.toUpperCase()} WASH</span><h2>Build today's wash.</h2><p>Choose the route and products. The journey will assemble itself from the real wash instructions.</p><div class="coating-list"><label class="coating"><input type="radio" name="coat" value="none" checked><span class="ring"></span><span><b>No coating</b><small>Wash without applying a body coating</small></span><em>—</em></label><label class="coating"><input type="radio" name="coat" value="turtlewax"><span class="ring"></span><span><b>Turtle Wax</b><small>180-day ceramic coating</small></span><em>180d</em></label><label class="coating"><input type="radio" name="coat" value="touchon"><span class="ring"></span><span><b>Touch-On</b><small>40-day ceramic top-up</small></span><em>40d</em></label></div><div class="coating-list"><label class="coating"><input type="radio" name="glass" value="regular" checked><span class="ring"></span><span><b>Regular glass clean</b><small>Streak-free glass</small></span><em>GLASS</em></label><label class="coating"><input type="radio" name="glass" value="rainx"><span class="ring"></span><span><b>Rain-X protection</b><small>90–120 day glass protection</small></span><em>90d+</em></label></div><div class="controls"><button class="secondary" id="back">Back</button><button class="primary" id="begin">Begin wash →</button></div></section>`;$('#back').onclick=home;$('#begin').onclick=()=>start()}
function getSteps(){let m;try{m=typeof MASTER_STEPS!=='undefined'?MASTER_STEPS:null}catch(e){m=null}if(!Array.isArray(m))return[];const sel=S.sel;return m.filter(x=>x&&x.type!=='decision'&&(!x.showIf||x.showIf(sel))).map((x,i)=>({phase:x.phase||'Wash',title:x.title||x.name||`Step ${i+1}`,body:x.body||x.instructions||x.text||[],warning:x.warning||null,minutes:x.minutes||x.dwellMinutes||x.timerMinutes||null,section:x.section||null,icon:x.icon||null}))}
function start(){S.sel={snowFoam:S.type==='deep'?'deep':'regular',coating:document.querySelector('input[name="coat"]:checked')?.value||'none',glass:document.querySelector('input[name="glass"]:checked')?.value||'regular',wheelsDeep:false,sillsDeep:false,ironFallout:false,claybarTarRemoval:false};S.steps=getSteps();if(!S.steps.length){V.innerHTML=`<section class="hero"><span class="eyebrow">DATA CONNECTION</span><h2>Wash data not loaded</h2><p>The new interface is ready, but MASTER_STEPS could not be read. Check that constants.js loads before gpt_app.js.</p><button class="primary" id="retry">Back to planner</button></section>`;$('#retry').onclick=home;return}S.i=0;S.screen='wash';renderWash()}
function renderWash(){const x=S.steps[S.i],n=S.steps.length,pct=(S.i+1)/n*100;clearInterval(S.timer);S.timer=null;S.remaining=0;T.textContent=S.type==='deep'?'Deep Wash':'Regular Wash';V.innerHTML=`<section class="wash-screen"><div class="wash-top"><div><span class="wash-phase">${esc(x.phase)}</span><h2>${esc(x.title)}</h2></div><div class="step-count">${String(S.i+1).padStart(2,'0')} / ${String(n).padStart(2,'0')}</div></div><div class="progress"><i style="width:${pct}%"></i></div><div class="journey-mini"><span>WASH JOURNEY</span><b>${esc(x.phase)}</b><span>${S.type.toUpperCase()}</span></div><article class="instruction-card"><div class="card-mark">${String(S.i+1).padStart(2,'0')}</div><div class="instruction-body">${renderContent(x.body,S.sel)}${renderWarning(x.warning,S.sel)}</div></article>${x.minutes?`<div class="timer live-timer"><small>DWELL TIME</small><strong id="timerValue">${fmt(x.minutes*60)}</strong><div><button id="timerStart">Start</button><button id="timerReset">Reset</button></div></div>`:''}<div class="nav"><button id="prev" ${S.i===0?'disabled':''}>←</button><span>${x.minutes?'Timer available · tap Start when product is applied':'Continue when ready'}</span><button id="next">${S.i===n-1?'Complete':'→'}</button></div></section>`;$('#next').onclick=()=>S.i<n-1?(S.i++,renderWash()):complete();$('#prev').onclick=()=>{if(S.i){S.i--;renderWash()}};const ts=$('#timerStart');if(ts)ts.onclick=timerStart;const tr=$('#timerReset');if(tr)tr.onclick=timerReset}
function fmt(s){return`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.max(0,s)%60).padStart(2,'0')}`}function timerStart(){if(S.timer)return;S.remaining=(S.steps[S.i].minutes||0)*60;$('#timerValue').textContent=fmt(S.remaining);S.timer=setInterval(()=>{S.remaining--;const e=$('#timerValue');if(e)e.textContent=fmt(S.remaining);if(S.remaining<=0){clearInterval(S.timer);S.timer=null;$('.live-timer')?.classList.add('done')}},1000)}function timerReset(){clearInterval(S.timer);S.timer=null;S.remaining=(S.steps[S.i].minutes||0)*60;if($('#timerValue'))$('#timerValue').textContent=fmt(S.remaining);$('.live-timer')?.classList.remove('done')}
function complete(){clearInterval(S.timer);S.timer=null;const log=GPT_STORE.getLog();log.push({date:new Date().toISOString(),washType:S.type,coating:S.sel.coating,glass:S.sel.glass,sections:S.steps.map(x=>x.section).filter(Boolean),completed:true});GPT_STORE.saveLog(log);T.textContent='Wash Complete';V.innerHTML=`<section class="hero complete"><span class="eyebrow">WASH COMPLETE</span><div class="complete-mark">✓</div><h2>Nice work.</h2><p>Your ${esc(S.type)} wash has been recorded. The next planner calculation can now use today's wash.</p><div class="cards"><div class="info-card"><h3>${S.steps.length} steps completed</h3><p>${esc(S.sel.coating==='none'?'No coating applied':S.sel.coating==='turtlewax'?'Turtle Wax applied':'Touch-On applied')} · ${esc(S.sel.glass==='rainx'?'Rain-X selected':'Regular glass clean')}</p></div></div><button class="primary" id="done">Back to planner</button></section>`;$('#done').onclick=home}
HOME.onclick=home;home();})();
