/* 14-day weather planning UI.
 * Daily cards can be selected to reveal daylight hourly conditions.
 */
(()=>{'use strict';
const icon=c=>{if(c===0)return'☀️';if(c<=2)return'🌤️';if(c===3)return'☁️';if(c<=48)return'🌫️';if(c<=57)return'🌦️';if(c<=67)return'🌧️';if(c<=77)return'❄️';if(c<=82)return'🌧️';if(c>=95)return'⛈️';return'⛅'};
const fmtDate=s=>new Date(`${s}T12:00:00`).toLocaleDateString([], {weekday:'short',day:'numeric',month:'short'});
const fmtHour=s=>new Date(s).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const daylight=hours=>hours.filter(h=>{const d=Number(h.hour);return d>=7&&d<=20&&h.isDay});
function windowForDay(hours,rules){const out=[];for(let i=0;i<hours.length-1;i++){const a=hours[i],b=hours[i+1];if(new Date(b.time)-new Date(a.time)!==3600000)continue;const good=x=>x.temp>=rules.tempMin&&x.temp<=rules.tempMax&&x.rainProbability>=rules.precipitationMin&&x.rainProbability<=rules.precipitationMax; if(good(a)&&good(b))out.push({start:a,end:b,score:Math.round((a.score+b.score)/2)});}return out}
function renderDayHours(day,result){
 const host=document.querySelector('.weather-hour-detail');if(!host)return;
 const hours=day?daylight(result.hourly.filter(h=>h.date===day)):[];const rules=result.rules;const windows=windowForDay(hours,h=>h);
 const good=h=>h.temp>=rules.tempMin&&h.temp<=rules.tempMax&&h.rainProbability>=rules.precipitationMin&&h.rainProbability<=rules.precipitationMax;
 const cards=hours.map(h=>`<div class="hour-cell ${good(h)?'hour-good':''}"><time>${fmtHour(h.time)}</time><i>${icon(h.code)}</i><strong>${Math.round(h.temp)}°</strong><span>${Math.round(h.rainProbability)}% rain</span></div>`).join('');
 const usable=[];for(let i=0;i<hours.length-1;i++)if(good(hours[i])&&good(hours[i+1]))usable.push(`${fmtHour(hours[i].time)}–${fmtHour(hours[i+1].time)}`);
 host.innerHTML=`<div class="hour-detail-head"><div><span class="eyebrow">DAYLIGHT HOURLY</span><strong>${fmtDate(day)}</strong></div><button type="button" class="hour-close" aria-label="Close">×</button></div><div class="hour-strip">${cards||'<p>No daylight hourly data available.</p>'}</div><div class="day-window-note ${usable.length?'day-window-good':'day-window-none'}"><b>${usable.length?'Usable wash time':'No 2-hour window meets all rules'}</b><span>${usable.length?usable.slice(0,3).join(' · '):'A day can still contain a short acceptable period — inspect the hourly conditions above.'}</span></div>`;
 host.querySelector('.hour-close')?.addEventListener('click',()=>{host.classList.remove('open');host.innerHTML=''});
 host.classList.add('open');
}
function renderWeatherPlan(result){
 const view=document.querySelector('#view');if(!view)return;const old=view.querySelector('.weather-planning');if(old)old.remove();
 const target=result.targetDate,best=result.bestAvailable,state=result.recommendation;
 const title=state==='ideal'?'A good wash window is available':state==='acceptable'?'There is a workable window':'No suitable window found';const tone=state==='ideal'?'good':state==='acceptable'?'maybe':'poor';
 const rec=best?`<div class="weather-recommendation ${tone}"><div><span class="eyebrow">${state==='ideal'?'RECOMMENDED WINDOW':'BEST AVAILABLE'}</span><strong>${fmtDate(best.date)} · ${fmtHour(best.start)}–${fmtHour(best.end)}</strong><p>${best.ideal?'Conditions meet the wash rules.':'Conditions are acceptable but not ideal — check the sky before starting.'}</p></div><span class="rec-score">${Math.round(best.score)}</span></div>`:`<div class="weather-recommendation poor"><div><span class="eyebrow">BEST AVAILABLE</span><strong>No reliable window yet</strong><p>A day may still contain a short usable period. Tap a day below to inspect the daylight hours.</p></div></div>`;
 const days=result.daily.map(d=>`<button type="button" class="forecast-day ${d.isTarget?'target':''}" data-weather-day="${d.date}"><small>${fmtDate(d.date)}</small><i>${icon(d.code)}</i><strong>${d.max}°</strong><span>${d.min}° · ${Math.round(d.rainProbability)}% rain</span>${d.isTarget?'<b class="target-badge">10 DAY TARGET</b>':''}</button>`).join('');
 const section=document.createElement('section');section.className='weather-planning';section.innerHTML=`<div class="planning-head"><div><span class="eyebrow">14 DAY OUTLOOK</span><h3>${title}</h3><p>${target?`Target wash day: <b>${fmtDate(target)}</b> · tap a day to inspect daylight.`:'Complete a wash to establish the next 10-day target.'}</p></div><span class="planning-mark">${state==='ideal'?'✓':state==='acceptable'?'~':'•'}</span></div>${rec}<div class="forecast-strip">${days}</div><div class="weather-hour-detail"></div>`;
 const hero=view.querySelector('.hero');if(hero)hero.insertAdjacentElement('afterend',section);else view.prepend(section);
 section.querySelectorAll('[data-weather-day]').forEach(btn=>btn.addEventListener('click',()=>{section.querySelectorAll('.forecast-day').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');renderDayHours(btn.dataset.weatherDay,result)}));
}
async function upgrade(){if(!window.GPT_WEATHER)return;try{const data=await GPT_WEATHER.fetch();const result=GPT_WEATHER.build(data);window.GPT_WEATHER_RESULT=result;renderWeatherPlan(result);const now=document.querySelector('.weather-now'),ring=document.querySelector('.weather-hours-ring');if(!now||!ring)return;const current=data.current;const h=result.hourly.filter(x=>x.time>=(current.time||'')).slice(0,5);now.innerHTML=`<span class="weather-icon">${icon(Number(current.weather_code))}</span><strong>${Math.round(current.temperature_2m)}°</strong><small>live conditions</small><b>${Math.round(current.precipitation||0)} mm</b>`;ring.innerHTML=h.map((x,i)=>`<span style="--slot:${i}">${fmtHour(x.time)}<i>${icon(x.code)}</i><b>${Math.round(x.temp)}° · ${Math.round(x.rainProbability)}%</b></span>`).join('');const status=document.querySelector('.status-line');if(status)status.innerHTML='<span class="status-dot"></span><strong>14-day forecast loaded</strong><span>Wash planning active</span>';}catch(e){console.warn('14-day weather planning unavailable',e)}}
window.GPT_WEATHER_UI={refresh:upgrade};const observer=new MutationObserver(()=>{if(document.querySelector('.weather-instrument')&&!document.querySelector('.weather-planning'))upgrade()});observer.observe(document.querySelector('#view')||document.body,{childList:true,subtree:true});setTimeout(upgrade,350);
})();