/* GPT Austral Wash Bay — standalone guided wash UI */
(()=>{'use strict';
const V=document.querySelector('#view'),T=document.querySelector('#pageTitle'),HOME=document.querySelector('#homeButton');
const S={screen:'home',type:null,sel:null,i:0,steps:[],timer:null,remaining:0,previousPhase:null};
const $=s=>document.querySelector(s);
const conditionalKeys=new Set(['noCoating','turtle','touchon','rainx','noRainx','claybarTarRemoval','wheelsDeep','ironFallout','snowFoamRegular','snowFoamDeep']);
const PHASE_META={
 'Before You Start':{colour:'setup',icon:'equipment'},'Wheel Pre-Wash':{colour:'wheels',icon:'spray'},'Wheels & Decontamination':{colour:'decon',icon:'spray'},'Snow Foam Pre-Wash':{colour:'foam',icon:'foam'},'Iron Fallout':{colour:'fallout',icon:'spray'},'Contact Wash':{colour:'contact',icon:'mitt'},'Tar Removal':{colour:'tar',icon:'mitt'},'Touch-On':{colour:'touchon',icon:'spray'},'Drying':{colour:'drying',icon:'towel'},'Rain-X: Application':{colour:'rainx',icon:'spray'},'Turtle Wax: Application':{colour:'turtle',icon:'coating'},'Final Checks':{colour:'finish',icon:'check'}};
function active(k,sel){const r={noCoating:()=>sel.coating==='none',turtle:()=>sel.coating==='turtlewax',touchon:()=>sel.coating==='touchon',rainx:()=>sel.glass==='rainx',noRainx:()=>sel.glass!=='rainx',claybarTarRemoval:()=>!!sel.claybarTarRemoval,wheelsDeep:()=>!!sel.wheelsDeep,ironFallout:()=>!!sel.ironFallout,snowFoamRegular:()=>sel.snowFoam==='regular',snowFoamDeep:()=>sel.snowFoam==='deep'};return r[k]?r[k]():false}
function renderValue(v,sel){if(v==null)return '';if(typeof v==='string')return `<p class="instruction-item">${v}</p>`;if(Array.isArray(v))return v.map(x=>renderValue(x,sel)).join('');if(typeof v==='object')return Object.entries(v).map(([k,val])=>conditionalKeys.has(k)?(active(k,sel)?renderValue(val,sel):''):`<div class="instruction-group"><h4>${esc(k)}</h4>${renderValue(val,sel)}</div>`).join('');return ''}
function renderWarning(v,sel){if(v==null)return '';const html=renderValue(v,sel).replaceAll('instruction-item','warning-item');return html?`<aside class="warning"><span class="warning-icon">!</span><div>${html}</div></aside>`:''}
function icon(name){return ({spray:'⌁',rinse:'◌',foam:'✦',bucket:'▣',mitt:'◒',towel:'▤',coating:'◇',polish:'◈',brush:'✧',door:'▱',equipment:'⚙',check:'✓'})[name]||'•'}
function esc(x){return String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function phaseClass(name){return (PHASE_META[name]?.colour||name||'wash').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function phaseInfo(){const map=[];S.steps.forEach((x,i)=>{let p=map.find(a=>a.name===x.phase);if(!p){p={name:x.phase,count:0,first:i};map.push(p)}p.count++});return map}
function journey(){const phases=phaseInfo();return `<div class="journey" aria-label="Wash progress"><div class="journey-track">${phases.map((p,i)=>{const completed=S.i>=p.first+p.count;const within=S.i>=p.first&&S.i<p.first+p.count;const progress=within?((S.i-p.first+1)/p.count)*100:completed?100:0;const meta=PHASE_META[p.name]||{};return `<button class="journey-phase ${within?'current':''} ${completed?'done':''} phase-${phaseClass(p.name)}" data-jump="${p.first}" aria-label="${esc(p.name)}"><i style="--phase-progress:${progress}%;--phase-colour:var(--zone-${meta.colour||'default'})">${i+1}</i></button>`}).join('<em></em>')}</div></div>`}
function home(){clearInterval(S.timer);S.timer=null;S.screen='home';T.textContent='Wash Planner';V.innerHTML=`<section class="hero dashboard"><div class="hero-copy"><span class="eyebrow">TODAY'S WASH WINDOW</span><h2>Ready when the conditions are.</h2><p>Your car, protection and weather — brought together in one glance.</p></div><div class="glance"><div><div class="orbit protection"><div><small>PROTECTION</small><strong>—</strong><span>checking</span></div></div><div class="glance-label">PROTECTION</div></div><div><div class="glance-detail"><span class="weather-icon">⛅</span><strong>—°</strong><small>weather loading</small><b>CHECKING</b></div><div class="glance-label">RIGHT NOW</div></div><div><div class="orbit weather-orbit"><div class="weather-hours"><span>—<br>◌<br>—</span><span>—<br>◌<br>—</span><span>—<br>◌<br>—</span><span>—<br>◌<br>—</span></div></div><div class="glance-label">NEXT HOURS</div></div></div><div class="status-line"><span class="status-dot"></span><strong>Wash planner ready</strong><span>Live weather integration next</span></div></section><section class="cards"><div class="info-card"><span class="eyebrow">WASH RHYTHM</span><h3>Choose your route</h3><p>The guided journey assembles only the instructions relevant to today's choices.</p></div><div class="info-card"><span class="eyebrow">PROTECTION</span><h3>Coating-aware from the first step</h3><p>Only one body coating can be selected per wash.</p></div></section><div class="wash-choice"><button class="choice action" data-type="regular"><h3>Regular wash <span>→</span></h3><p>Routine maintenance · streamlined guided route</p></button><button class="choice action" data-type="deep"><h3>Deep wash <span>→</span></h3><p>Full clean · decontamination · detail</p></button></div>`;document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>setup(b.dataset.type))}
function setup(type){S.type=type;T.textContent='New Wash';V.innerHTML=`<section class="hero setup"><span class="eyebrow">${type.toUpperCase()} WASH</span><h2>Build today's wash.</h2><p>Choose the products and optional treatments. The journey will assemble itself.</p><div class="coating-list"><label class="coating"><input type="radio" name="coat" value="none" checked><span class="ring"></span><span><b>No coating</b><small>No body coating applied</small></span><em>—</em></label><label class="coating"><input type="radio" name="coat" value="turtlewax"><span class="ring"></span><span><b>Turtle Wax</b><small>180-day ceramic coating</small></span><em>180d</em></label><label class="coating"><input type="radio" name="coat" value="touchon"><span class="ring"></span><span><b>Touch-On</b><small>40-day ceramic top-up</small></span><em>40d</em></label></div><div class="coating-list"><label class="coating"><input type="radio" name="glass" value="regular" checked><span class="ring"></span><span><b>Regular glass clean</b><small>Streak-free glass</small></span><em>GLASS</em></label><label class="coating"><input type="radio" name="glass" value="rainx"><span class="ring"></span><span><b>Rain-X protection</b><small>Glass protection</small></span><em>90d+</em></label></div><div class="controls"><button class="secondary" id="back">Back</button><button class="primary" id="begin">Begin wash →</button></div></section>`;$('#back').onclick=home;$('#begin').onclick=start}
function getSteps(){const m=window.GPT_MASTER_STEPS;if(!Array.isArray(m))return[];return m.filter(x=>x&&x.type!=='decision'&&(!x.showIf||x.showIf(S.sel))).map(x=>({phase:x.phase||'Wash',title:x.title||x.name||'Step',body:x.body??[],warning:x.warning??null,timerSec:Number.isFinite(Number(x.timerSec))?Number(x.timerSec):(Number.isFinite(Number(x.dwellSeconds))?Number(x.dwellSeconds):(Number.isFinite(Number(x.minutes))?Number(x.minutes)*60:null)),timerLabel:x.timerLabel||'Dwell time',timerRange:x.timerRange||'',section:x.section||null,icon:x.icon||PHASE_META[x.phase]?.icon||'equipment'}))}
function start(){S.sel={snowFoam:S.type==='deep'?'deep':'regular',coating:document.querySelector('input[name="coat"]:checked')?.value||'none',glass:document.querySelector('input[name="glass"]:checked')?.value||'regular',wheelsDeep:false,sillsDeep:false,ironFallout:false,claybarTarRemoval:false};S.steps=getSteps();if(!S.steps.length){V.innerHTML=`<section class="hero"><span class="eyebrow">DATA CONNECTION</span><h2>Wash data not loaded</h2><p>The GPT master-step data could not be read.</p><button class="primary" id="retry">Back to planner</button></section>`;$('#retry').onclick=home;return}S.i=0;S.screen='wash';S.previousPhase=null;renderWash()}
function renderWash(direction='none'){const x=S.steps[S.i],n=S.steps.length,pct=(S.i+1)/n*100,meta=PHASE_META[x.phase]||{};const phaseChanged=S.previousPhase!==null&&S.previousPhase!==x.phase;const showIntro=phaseChanged;S.previousPhase=x.phase;clearInterval(S.timer);S.timer=null;S.remaining=x.timerSec||0;V.innerHTML=`<section class="wash-screen phase-${phaseClass(x.phase)}" style="--phase-colour:var(--zone-${meta.colour||'default'})">${journey()}<header class="wash-heading"><div class="phase-title"><span class="phase-icon">${icon(x.icon)}</span><div><span class="phase-kicker">${esc(x.phase||'Wash')}</span><h2>${esc(x.title)}</h2></div></div><strong class="step-counter">${String(S.i+1).padStart(2,'0')} <span>/ ${String(n).padStart(2,'0')}</span></strong></header><div class="progress" aria-label="Overall wash progress"><i style="width:${pct}%"></i></div><article class="instruction-card enter-${direction}"><div class="card-mark">${String(S.i+1).padStart(2,'0')}</div><div class="instruction-body">${renderValue(x.body,S.sel)}${renderWarning(x.warning,S.sel)}</div></article>${x.timerSec?`<div class="timer live-timer"><div class="timer-head"><small>${esc(x.timerLabel)}</small><span>${esc(x.timerRange)}</span></div><strong id="timerValue">${fmt(x.timerSec)}</strong><div><button id="timerStart">Start timer</button><button id="timerReset">Reset</button></div></div>`:''}<div class="nav"><button id="prev" ${S.i===0?'disabled':''} aria-label="Previous step">←</button><span>${x.timerSec?'Start the timer when the product is applied':'Continue when ready'}</span><button id="next">${S.i===n-1?'Complete':'Next →'}</button></div>${showIntro?`<div class="phase-intro phase-${phaseClass(x.phase)}" aria-hidden="true"><div><span>${icon(x.icon)}</span><small>ENTERING ZONE</small><h3>${esc(x.phase)}</h3><i></i></div></div>`:''}</section>`;document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{S.i=Number(b.dataset.jump);renderWash('forward')});$('#next').onclick=()=>S.i<n-1?(S.i++,renderWash('forward')):complete();$('#prev').onclick=()=>{if(S.i){S.i--;renderWash('back')}};const ts=$('#timerStart');if(ts)ts.onclick=timerStart;const tr=$('#timerReset');if(tr)tr.onclick=timerReset;enableSwipe();enableKeyboard();animateItems();if(showIntro)window.setTimeout(()=>{$('.phase-intro')?.classList.add('hide');window.setTimeout(()=>$('.phase-intro')?.remove(),450)},1050)}
function animateItems(){document.querySelectorAll('.instruction-body .instruction-item').forEach((el,i)=>{el.style.animationDelay=`${Math.min(i*55,220)}ms`})}
function enableSwipe(){let sx=0,sy=0;const card=$('.instruction-card');if(!card)return;card.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});card.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.25){if(dx<0&&S.i<S.steps.length-1){S.i++;renderWash('forward')}else if(dx>0&&S.i>0){S.i--;renderWash('back')}}},{passive:true})}
function enableKeyboard(){document.onkeydown=e=>{if(S.screen!=='wash')return;if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();if(S.i<S.steps.length-1){S.i++;renderWash('forward')}else complete()}if(e.key==='ArrowLeft'){e.preventDefault();if(S.i>0){S.i--;renderWash('back')}}}}
function fmt(s){s=Math.max(0,Math.round(s));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function timerStart(){if(S.timer)return;S.timer=setInterval(()=>{S.remaining--;const e=$('#timerValue');if(e)e.textContent=fmt(S.remaining);if(S.remaining<=0){clearInterval(S.timer);S.timer=null;$('.live-timer')?.classList.add('done');const b=$('#timerStart');if(b)b.textContent='Complete ✓'}},1000)}
function timerReset(){clearInterval(S.timer);S.timer=null;S.remaining=S.steps[S.i].timerSec||0;const e=$('#timerValue');if(e)e.textContent=fmt(S.remaining);$('.live-timer')?.classList.remove('done');const b=$('#timerStart');if(b)b.textContent='Start timer'}
function complete(){clearInterval(S.timer);S.timer=null;const log=GPT_STORE.getLog();log.push({date:new Date().toISOString(),washType:S.type,coating:S.sel.coating,glass:S.sel.glass,sections:S.steps.map(x=>x.section).filter(Boolean),completed:true});GPT_STORE.saveLog(log);T.textContent='Wash Complete';V.innerHTML=`<section class="hero complete"><span class="eyebrow">WASH COMPLETE</span><div class="complete-mark">✓</div><h2>Nice work.</h2><p>Your ${esc(S.type)} wash has been recorded.</p><div class="cards"><div class="info-card"><h3>${S.steps.length} steps completed</h3><p>${esc(S.sel.coating==='none'?'No coating applied':S.sel.coating==='turtlewax'?'Turtle Wax applied':'Touch-On applied')} · ${esc(S.sel.glass==='rainx'?'Rain-X selected':'Regular glass clean')}</p></div></div><button class="primary" id="done">Back to planner</button></section>`;$('#done').onclick=home}
HOME.onclick=home;home();})();
