/* GPT Austral Wash Bay — new application shell.
   This is intentionally independent of the legacy renderer. It will consume the existing
   MASTER_STEPS content in a later integration pass rather than copying instruction text. */
(function(){'use strict';
const $=s=>document.querySelector(s),view=$('#view'),title=$('#pageTitle');
const state={screen:'home',washType:null,index:0,steps:[]};
function home(){state.screen='home';title.textContent='Wash Planner';view.innerHTML=`<section class="hero"><span class="eyebrow">TODAY'S WASH</span><h2>Make the next wash count.</h2><p class="muted">Weather first. Protection status second. Then a calm, guided wash from start to finish.</p><div class="grid"><button class="action" id="regular"><strong>Regular wash</strong><span>Routine maintenance wash</span></button><button class="action" id="deep"><strong>Deep wash</strong><span>Full decontamination and detail</span></button></div></section><div class="section-label">PLANNING</div><div class="grid"><button class="action"><strong>Weather outlook</strong><span>Choose the best window around your wash cycle.</span></button><button class="action"><strong>Wash log</strong><span>Your history, products and protection timeline.</span></button></div>`;$('#regular').onclick=()=>setup('regular');$('#deep').onclick=()=>setup('deep')}
function setup(type){state.screen='setup';state.washType=type;title.textContent='New Wash';view.innerHTML=`<section class="hero"><span class="eyebrow">${type.toUpperCase()} WASH</span><h2>Set up your wash.</h2><p class="muted">Choose your coating and start when you're ready. The guided wash will handle the sequence.</p><div class="section-label">COATING</div><label class="choice"><span><strong>Turtle Wax</strong><br><small>Long-term ceramic protection</small></span><input type="radio" name="coat" value="turtle"></label><label class="choice"><span><strong>Touch-On</strong><br><small>Fast ceramic top-up</small></span><input type="radio" name="coat" value="touchon"></label><label class="choice"><span><strong>No coating</strong><br><small>Skip coating this wash</small></span><input type="radio" name="coat" value="none" checked></label><div class="controls"><button class="secondary" id="back">Back</button><button class="primary" id="begin">Begin wash</button></div></section>`;$('#back').onclick=home;$('#begin').onclick=()=>start()}
function start(){state.screen='wash';title.textContent=state.washType==='deep'?'Deep Wash':'Regular Wash';/* Integration point: MASTER_STEPS will be mapped here. */view.innerHTML=`<section class="wash-head"><div><span class="eyebrow">GUIDED WASH</span><h2 style="margin:4px 0">Ready when you are.</h2></div><span class="muted">01 / 01</span></section><div class="progress"><i style="width:100%"></i></div><div class="journey"><span class="active">Preparation</span><span>Pre-wash</span><span>Wash</span><span>Rinse</span><span>Dry</span><span>Protection</span></div><article class="instruction"><div><div class="phase">PREPARATION</div><h2>Wash setup</h2><div class="instruction-content"><p>Your new guided wash interface is ready. The next integration will populate this screen directly from <b>MASTER_STEPS</b>, preserving every existing instruction and conditional rule.</p></div></div><div><div class="controls"><button class="secondary" id="prev">Previous</button><button class="primary" id="next">Next</button></div></div></article><div class="timer"><small>DWELL TIMER</small><strong>00:00</strong><button>Start timer</button></div></section>`}
$('#homeButton').onclick=home;home();
})();